<a href="https://colab.research.google.com/github/akshitagupta15june/sleep_apneaML/blob/master/adarsh.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [6]:
from tensorflow import keras
import sklearn
import numpy as np
import pandas as pd
from tensorflow.keras.layers import Dense,Dropout,LSTM
from tensorflow.keras.models import Sequential
from google.colab import files
#uploaded = files.upload()

In [10]:
df='sleeep_apnea_data.xlsx'
main_df=pd.read_excel(df,'male')

# New Section

In [12]:
#df=sklearn.utils.shuffle(main_df)
df=main_df.sample(frac=1).reset_index(drop=True)
df.dropna(inplace=True)


In [13]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

In [15]:
df.Gender=le.fit_transform(df.Gender)

In [16]:
def fun(num): 
  
    if num<=30: 
        return 0
    else: 
        return 1

In [17]:
df['status']=df.AHI.apply(fun)
status=["negative","positive"]

In [18]:
df

Gender   BQ   ESS        BMI  ...  Buttock   Age        AHI  status
0          1  0.0   5.0  21.469150  ...     93.5  55.0   4.897959       0
1          0  1.0  16.0  21.644121  ...     90.0  68.0  14.830000       0
2          1  0.0  11.0  32.238501  ...    112.0  33.0  68.297872       1
3          0  0.0  13.0  18.662015  ...     83.5  37.0   2.540000       0
4          1  0.0  13.0  23.120624  ...     93.0  41.0  77.804154       1
...      ...  ...   ...        ...  ...      ...   ...        ...     ...
5240       1  1.0  18.0  27.990363  ...    101.0  35.0  84.307692       1
5241       1  0.0  12.0  22.229062  ...     88.3  23.0   0.346821       0
5242       1  0.0  14.0  28.240190  ...    104.5  34.0  62.881356       1
5243       1  0.0   8.0  29.104369  ...    104.0  59.0   9.911504       0
5244       0  0.0   7.0  17.799929  ...     88.0  34.0   0.000000       0

[5241 rows x 13 columns]

In [19]:
#column_maxes = df.max()
#column_maxes.drop(['Gender'],inplace=True)
#df_max = column_maxes.max()
#normalized_df = df / df_max



In [20]:
df1=df.drop(['Gender','status'],1)

In [21]:
df1['Gender']=df['Gender']
df1["status"]=df['status']

In [22]:
df1

BQ   ESS        BMI  Weight  ...   Age        AHI  Gender  status
0     0.0   5.0  21.469150    65.0  ...  55.0   4.897959       1       0
1     1.0  16.0  21.644121    52.0  ...  68.0  14.830000       0       0
2     0.0  11.0  32.238501   101.0  ...  33.0  68.297872       1       1
3     0.0  13.0  18.662015    46.0  ...  37.0   2.540000       0       0
4     0.0  13.0  23.120624    70.0  ...  41.0  77.804154       1       1
...   ...   ...        ...     ...  ...   ...        ...     ...     ...
5240  1.0  18.0  27.990363    79.0  ...  35.0  84.307692       1       1
5241  0.0  12.0  22.229062    65.0  ...  23.0   0.346821       1       0
5242  0.0  14.0  28.240190    85.5  ...  34.0  62.881356       1       1
5243  0.0   8.0  29.104369    80.2  ...  59.0   9.911504       1       0
5244  0.0   7.0  17.799929    45.0  ...  34.0   0.000000       0       0

[5241 rows x 13 columns]

In [23]:
x=np.array(df1.drop(['AHI',"status"],1))
y=np.array(df1['status'])

In [28]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.20)

In [30]:
from sklearn import linear_model,svm, tree
from sklearn.linear_model import LogisticRegression,Ridge
from sklearn.neighbors import KNeighborsClassifier
from sklearn.tree import DecisionTreeRegressor

In [31]:
model1= linear_model.LinearRegression(fit_intercept=True)
svr_poly = svm.SVR(kernel='linear', C=100, gamma='auto', degree=3, epsilon=.1,coef0=1)
dtree = DecisionTreeRegressor(max_depth=10, min_samples_leaf=0.13, random_state=3)
sv=svm.SVC(C=10,kernel='linear')

In [32]:
sv.fit(x_train,y_train)

SVC(C=10, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [33]:
acc=sv.score(x_test,y_test)

In [50]:
acc

0.7702573879885606

In [35]:
p1=sv.predict(x_test)

In [37]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Activation,Flatten,Dropout
from tensorflow.keras.models import Model
from tensorflow.keras.optimizers import Adam
#from tensorflow.python.keras.layers.kernelized import RandomFourierFeatures
from tensorflow.keras import layers


In [56]:
model=Sequential()
model.add(Dense(30,activation='relu',input_shape=[x_train.shape[1]]))
model.add(Dropout(.02))
model.add(Dense(10,activation='relu'))
model.add(Dropout(.02))
model.add(Dense(50,activation='relu'))
#model.add(Dense(50,activation='relu'))

model.add(Dense(1,activation='sigmoid'))
model.compile(Adam(lr=0.01),loss='binary_crossentropy',metrics=['accuracy'])
model.fit(x_train,y_train,epochs=100,validation_split=0.2)

Epoch 1/100
105/105 [==============================] - 0s 3ms/step - loss: 0.6935 - accuracy: 0.6612 - val_loss: 0.5078 - val_accuracy: 0.7676
Epoch 2/100
105/105 [==============================] - 0s 2ms/step - loss: 0.5353 - accuracy: 0.7274 - val_loss: 0.4907 - val_accuracy: 0.7628
Epoch 3/100
105/105 [==============================] - 0s 2ms/step - loss: 0.5337 - accuracy: 0.7325 - val_loss: 0.5143 - val_accuracy: 0.7557
Epoch 4/100
105/105 [==============================] - 0s 2ms/step - loss: 0.5096 - accuracy: 0.7411 - val_loss: 0.5286 - val_accuracy: 0.7366
Epoch 5/100
105/105 [==============================] - 0s 2ms/step - loss: 0.5198 - accuracy: 0.7334 - val_loss: 0.5056 - val_accuracy: 0.7592
Epoch 6/100
105/105 [==============================] - 0s 2ms/step - loss: 0.5127 - accuracy: 0.7456 - val_loss: 0.4895 - val_accuracy: 0.7640
Epoch 7/100
105/105 [==============================] - 0s 2ms/step - loss: 0.5008 - accuracy: 0.7444 - val_loss: 0.4843 - val_accuracy: 0.7783

In [40]:
model.predict([[  0.  ,   0.  ,  24.22,  70.  , 170.  ,  58.5 ,  42.  ,  92.5 ,
        99.  ,  60.  ,   1. ]])


array([[0.4385051]], dtype=float32)

In [41]:
p=model.predict(x_test)

In [42]:
p[1047]

array([0.4385051], dtype=float32)

In [43]:
x_test[9]

array([  0.        ,   7.        ,  20.58377277,  48.5       ,
       153.5       ,  55.        ,  30.        ,  71.        ,
        88.        ,  62.        ,   0.        ])

In [44]:
y_test[1047]

0

In [46]:
keras_file="model_tensor"
keras.models.save_model(model,keras_file)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.
INFO:tensorflow:Assets written to: model_tensor/assets


In [48]:
import tensorflow
converter = tensorflow.lite.TFLiteConverter.from_saved_model(keras_file)
tflite_model=converter.convert()
open("tflitemodel.tflite","wb").write(tflite_model)

7136